import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DataFolderProvider } from "@/providers/Datafolderprovider";
import AppProviders from "./app-providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OAUOIR",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>{children}</AppProviders>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
